### ISSUE TITLE
Crash on ctrl c

### ISSUE THREAD

**Issue by jstnhlj** [magnars/autolint#8]
Typing ctrl c makes autolint crash with this stack:

83 clean files, more than 1902 errors in 134 dirty files
^CChecking all files. Interrupt a second time to quit

/usr/local/lib/node_modules/autolint/vendor/jslint.js:1214
            if (line >= lines.length) {
                             ^
TypeError: Cannot read property 'length' of undefined
    at next_line (/usr/local/lib/node_modules/autolint/vendor/jslint.js:1214:30)
    at Object.init (/usr/local/lib/node_modules/autolint/vendor/jslint.js:1712:17)
    at Object.JSLint [as check](/usr/local/lib/node_modules/autolint/vendor/jslint.js:6034:13)
    at EventEmitter.check (/usr/local/lib/node_modules/autolint/lib/jslint-linter.js:7:28)
    at EventEmitter.checkFile (/usr/local/lib/node_modules/autolint/lib/jslint-linter.js:12:23)
    at [object Object].<anonymous> (fs.js:88:5)
    at [object Object].emit (events.js:67:17)
    at fs.js:1058:12
    at /usr/local/lib/node_modules/autolint/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:56:5
    at Object.oncomplete (/usr/local/lib/node_modules/autolint/node_modules/glob/node_modules/graceful-fs/graceful-fs.js:68:5)

**Comment by magnars** [comment]
I was able to reproduce it at last. :)
